<?php
add_action('acf/init', function() {
    if (!function_exists('acf_add_local_field_group')) return;

    // ── 商品フィールドグループ ────────────────────────────────────────────────
    acf_add_local_field_group([
        'key'             => 'group_greige_product',
        'title'           => '商品情報',
        'label_placement' => 'top',
        'position'        => 'normal',
        'style'           => 'default',
        'fields'          => [
            [
                'key'     => 'field_gp_gas_id',
                'label'   => 'GAS商品ID',
                'name'    => 'gas_product_id',
                'type'    => 'text',
                'instructions' => 'GAS PRODUCT_POOL の product_id（例: P0001）',
                'required' => 0,
                'wrapper'  => ['width' => '50'],
            ],
            [
                'key'      => 'field_gp_brand',
                'label'    => 'ブランド名',
                'name'     => 'product_brand',
                'type'     => 'text',
                'required' => 1,
                'wrapper'  => ['width' => '50'],
            ],
            [
                'key'      => 'field_gp_price',
                'label'    => '価格（通常）',
                'name'     => 'product_price',
                'type'     => 'number',
                'min'      => 0,
                'required' => 0,
                'wrapper'  => ['width' => '33'],
            ],
            [
                'key'      => 'field_gp_sale_price',
                'label'    => 'セール価格',
                'name'     => 'product_sale_price',
                'type'     => 'number',
                'min'      => 0,
                'required' => 0,
                'wrapper'  => ['width' => '33'],
            ],
            [
                'key'           => 'field_gp_currency',
                'label'         => '通貨',
                'name'          => 'product_currency',
                'type'          => 'select',
                'choices'       => ['JPY' => '円（JPY）', 'USD' => 'USD', 'EUR' => 'EUR'],
                'default_value' => 'JPY',
                'allow_null'    => 0,
                'required'      => 0,
                'wrapper'       => ['width' => '34'],
            ],
            [
                'key'      => 'field_gp_product_url',
                'label'    => '商品URL（公式）',
                'name'     => 'product_url',
                'type'     => 'url',
                'required' => 0,
                'wrapper'  => ['width' => '100'],
            ],
            [
                'key'      => 'field_gp_aff_rakuten',
                'label'    => 'アフィリエイト：楽天市場',
                'name'     => 'affiliate_rakuten',
                'type'     => 'url',
                'required' => 0,
                'wrapper'  => ['width' => '50'],
            ],
            [
                'key'      => 'field_gp_aff_amazon',
                'label'    => 'アフィリエイト：Amazon',
                'name'     => 'affiliate_amazon',
                'type'     => 'url',
                'required' => 0,
                'wrapper'  => ['width' => '50'],
            ],
            [
                'key'      => 'field_gp_aff_yahoo',
                'label'    => 'アフィリエイト：Yahoo!ショッピング',
                'name'     => 'affiliate_yahoo',
                'type'     => 'url',
                'required' => 0,
                'wrapper'  => ['width' => '50'],
            ],
            [
                'key'      => 'field_gp_aff_official',
                'label'    => 'アフィリエイト：公式サイト',
                'name'     => 'affiliate_official',
                'type'     => 'url',
                'required' => 0,
                'wrapper'  => ['width' => '50'],
            ],
            [
                'key'      => 'field_gp_material',
                'label'    => '素材',
                'name'     => 'product_material',
                'type'     => 'text',
                'required' => 0,
                'wrapper'  => ['width' => '33'],
            ],
            [
                'key'      => 'field_gp_color',
                'label'    => 'カラー',
                'name'     => 'product_color',
                'type'     => 'text',
                'required' => 0,
                'wrapper'  => ['width' => '33'],
            ],
            [
                'key'      => 'field_gp_size',
                'label'    => 'サイズ',
                'name'     => 'product_size',
                'type'     => 'text',
                'required' => 0,
                'wrapper'  => ['width' => '34'],
            ],
            [
                'key'      => 'field_gp_description',
                'label'    => '商品説明',
                'name'     => 'product_description',
                'type'     => 'textarea',
                'rows'     => 3,
                'required' => 0,
            ],
            [
                'key'          => 'field_gp_editor_comment',
                'label'        => '編集コメント',
                'name'         => 'editor_comment',
                'type'         => 'textarea',
                'rows'         => 3,
                'instructions' => 'GREIGEとして選んだ理由・編集視点のコメント。',
                'required'     => 0,
            ],
            [
                'key'          => 'field_gp_ext_image',
                'label'        => '商品画像URL（外部・メイン）',
                'name'         => 'product_external_image',
                'type'         => 'url',
                'instructions' => 'アイキャッチ未設定時のフォールバック。',
                'required'     => 0,
            ],
            [
                'key'          => 'field_gp_extra_images',
                'label'        => '追加画像URL（複数・改行区切り）',
                'name'         => 'product_extra_images',
                'type'         => 'textarea',
                'rows'         => 4,
                'instructions' => '楽天などの商品画像URLを1行に1つ貼り付け。サムネイルとして表示されます。',
                'required'     => 0,
            ],
        ],
        'location' => [[['param' => 'post_type', 'operator' => '==', 'value' => 'greige_product']]],
    ]);
});
